about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about_me, name='about'),
    path('thanks/', views.thanks, name='thanks'),
]

game_reviews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from reviews import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/games/', include('user_games.urls', namespace='user_games')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('about/', include('about.urls'), name='about-urls'),
    path('thanks/', views.thanks, name='thanks'),
    path('', views.HomeView.as_view(), name='home'),  # Ensure home view is defined
    path('reviews/', include('reviews.urls')),  # Include reviews URLs
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_games/urls.py
from django.urls import path
from . import views

app_name = 'user_games'

urlpatterns = [
    path('', views.user_games, name='user_games'),
    path('edit/<int:game_id>/', views.edit_game, name='edit_game'),
]

templates/base.html
{% load static %}
{% url 'reviews' as reviews_url %}
{% url 'about' as about_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}
{% url 'upload_game' as upload_game_url %}
{% url 'user_games' as user_games_url %}

<!-- Base Page -->
<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Game Reviews{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/cf468e5aaf.js" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">

    <!-- Custom CSS -->
     {% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark dark-bg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Anteskog's</a>
            <button id="navbar-icon" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa-solid fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == reviews_url %}active{% endif %}" aria-current="page" href="{% url 'reviews' %}">Reviews</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == about_url %}active{% endif %}" aria-current="page"
                            href="{% url 'about' %}">About</a>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == upload_game_url %}active{% endif %}" aria-current="page"
                            href="{% url 'upload_game' %}">Upload a Game</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == user_games_url %}active{% endif %}" aria-current="page"
                            href="{% url 'user_games:user_games' %}">Your Games</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}

                </ul>
                <span class="navbar-text text-muted">
                    Explore the world of gaming
                </span>
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0 main-bg user-box">
        {% if user.is_authenticated %}
        <p class="text-end m-3">You are logged in as {{ user }}</p>
        {% else %}
        <p class="text-end m-3">You are not logged in</p>
        {% endif %}

        <!-- Display messages -->
        {% if messages %}
        <div id="alert-container text-center">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

    </main>

<!-- Footer -->
<footer class="footer dark-bg">
    <div class="container text-center">
        <p class="m-0 text-center">Made by Johan.A</p>
        <p class="m-0 text-center">Follow me: 
            <a href="https://www.facebook.com" target="_blank" class="text-muted"><i class="fab fa-facebook-square ms-3"></i></a>
            <a href="https://www.twitter.com" target="_blank" class="text-muted"><i class="fab fa-twitter-square ms-3"></i></a>
            <a href="https://www.instagram.com" target="_blank" class="text-muted"><i class="fab fa-instagram-square ms-3"></i></a>
            <a href="https://www.youtube.com" target="_blank" class="text-muted"><i class="fab fa-youtube-square ms-3"></i></a>
        </p>
        <p class="m-0 text-center">&copy; 2025 Game Reviews</p>
    </div>
</footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    
<script>
    document.addEventListener("DOMContentLoaded", function() {

        const alerts = document.querySelectorAll('.alert');


        alerts.forEach(alert => {
            setTimeout(() => {
                alert.classList.remove('show');
                alert.classList.add('fade');
            }, 5000);
        });
    });
</script>
    {% block extra_js %}
    {% endblock %}
</body>

</html>